# Generated by Django 5.2.4 on 2026-03-19 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_alter_ordermodel_paid_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='card_number',
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?[0-9]{10,15}$', message='Enter a valid phone number')]),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='pin_code',
            field=models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{4,6}$', message='PIN code must be 4-6 digits')]),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='StripeModel',
        ),
    ]
