# Generated by Django 5.2.4 on 2026-03-20 00:00

import django.core.validators
import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_category_alter_product_options_product_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Auntor Shopping Mall', max_length=120)),
                ('hero_eyebrow', models.CharField(default='Fresh & Local', max_length=120)),
                ('hero_title', models.CharField(default='Quality Groceries & Essentials Delivered to Your Door', max_length=255)),
                ('hero_subtitle', models.TextField(default='Shop fresh produce, pantry staples, electronics, and household essentials across Bangladesh.')),
                ('support_email', models.EmailField(default='help@auntor.com.bd', max_length=254)),
                ('support_phone', models.CharField(default='+880 1XXX-XXXXXX', max_length=40)),
                ('footer_address', models.CharField(default='Dhaka, Bangladesh', max_length=255)),
                ('hero_background_image', models.ImageField(blank=True, null=True, upload_to='site/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), product.models.validate_image_size])),
                ('promo_background_image', models.ImageField(blank=True, null=True, upload_to='site/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), product.models.validate_image_size])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]